### PR TITLE
[IMP] store total_overtime field

### PR DESCRIPTION
**Pull request by victor-champonnois**
Linked to [this PR](https://github.com/coopiteasy/cie-custom/pull/44) and to this [task](https://gestion.coopiteasy.be/web#id=4361&view_type=form&model=project.task&action=479)

- Need to store the computed field `total_overtime` in order to use it in a pivot view in [provelo_custom](https://github.com/coopiteasy/cie-custom/tree/12.0/provelo_custom)

Note : running pre-commit changed other parts of the file. Should I remove these changes?

### CODE REVIEW

**Review by robinkeunen — CHANGES_REQUESTED** [review]
Maybe don't bother here but when precommit changes stuff unrelated to your PR, try to isolate it in a separate commit.

When you do not store the value of a field, you can rely on the fact that the function will me computed every time the object is loaded. If you store it, you must list all the field you use in your computed function.

```py
    @api.multi
    @api.depends("timesheet_sheet_ids.active")
    def _compute_total_overtime(self):
        """
        Computes total overtime since employee's overtime start date
        """
        for employee in self:
            sheets = self.env["hr_timesheet.sheet"].search(
                [
                    ("employee_id", "=", employee.id),
                    ("date_end", ">=", employee.overtime_start_date),
                ]
            )
            overtime = sum(sheet.timesheet_overtime for sheet in sheets)
            employee.total_overtime = employee.initial_overtime + overtime
```

**Comment by victor-champonnois** [comment]
> When you do not store the value of a field, you can rely on the fact that the function will me computed every time the object is loaded. If you store it, you must list all the field you use in your computed function.
> 
> ```python
>     @api.multi
>     @api.depends("timesheet_sheet_ids.active")
>     def _compute_total_overtime(self):
>         """
>         Computes total overtime since employee's overtime start date
>         """
>         for employee in self:
>             sheets = self.env["hr_timesheet.sheet"].search(
>                 [
>                     ("employee_id", "=", employee.id),
>                     ("date_end", ">=", employee.overtime_start_date),
>                 ]
>             )
>             overtime = sum(sheet.timesheet_overtime for sheet in sheets)
>             employee.total_overtime = employee.initial_overtime + overtime
> ```
Thanks for your review. I am not sure I understand your example, since the field "timesheet_sheet_ids.active" is in the `api.depends`, but is not used in the method. Therefore I am not sure I understood your point... :slightly_smiling_face:

**Comment by robinkeunen** [comment]
@coccinouille I isolated the code of the compute function as is in my comment :-)

The code should look like:

```py
    @api.multi
    @api.depends("timesheet_sheet_ids.active", "timesheet_sheet_ids.active", "overtime_start_date", "initial_overtime")
    def _compute_total_overtime(self):
        """
        Computes total overtime since employee's overtime start date
        """
        for employee in self:
            sheets = self.env["hr_timesheet.sheet"].search(
                [
                    ("employee_id", "=", employee.id),
                    ("date_end", ">=", employee.overtime_start_date),
                ]
            )
            overtime = sum(sheet.timesheet_overtime for sheet in sheets)
            employee.total_overtime = employee.initial_overtime + overtime
```

**Comment by huguesdk** [comment]
it goes farther than that. the overtime depends also on the timesheet lines (`account.analytic.line`) and their amount of time, the contracts of the employee,… it’s a little tricky to find all fields on which this depends. not impossible, but easy to get wrong.

**Comment by victor-champonnois** [comment]
Storing the "total_overtime" field in the hr_timesheet.sheet model rather than in the hr.employee model.

**Pull request closed without merging**
