### PR TITLE
[REF] hr_timesheet_overtime: Add working_time, refactor timesheet_overtime[_trimmed], adjust UI

### PR DESCRIPTION
**Pull request by carmenbianca**
Slight refactoring for work in https://github.com/coopiteasy/cie-custom/pull/61

### CODE REVIEW

**Comment by carmenbianca** [comment]
~~TODO: Enable CI on this repo.~~

**Review by huguesdk — APPROVED** [review]
nice and clean addition!

since the existing property is called `total_time`, shouldn’t this new one also be named something with `_time` instead of `_hours`? how do we say "the amount time the employee is supposed to work", but shorter? ☺ i see that the current name makes sense since there is a called `get_worked_hours`. maybe rename this one to be consistent with field names from the `hr_timesheet_sheet` module?

**Comment by carmenbianca** [comment]
Huh, this makes no sense. I rebased on top of 12.0, and suddenly [e86e22d](https://github.com/coopiteasy/cie-timesheet/pull/16/commits/e86e22d7d42a0a775769da8dd7b4a7ed878ac494) broke the tests somehow.

> maybe rename this one to be consistent with field names from the hr_timesheet_sheet module?

@huguesdk Tried doing this in [390ef88](https://github.com/coopiteasy/cie-timesheet/pull/16/commits/390ef88491d5efcc16af14d955d0a5b63735c389). The renamed fields shouldn't break anything because they're computed. I also grepped, and no downstream module is impacted by this commit.

**Comment by carmenbianca** [comment]
@huguesdk Requesting another review after some refactoring. It's best to review these commit-by-commit.

**Comment by carmenbianca** [comment]
My word, I messed up the rebasing here. Giving it another go.

**Comment by carmenbianca** [comment]
Much better :ok_woman:

**Review by huguesdk — APPROVED** [review]
lgtm! 🎉

please rename the pull request’s description to match the changes. the branch name is a little suprising also. ☺ but it cannot be changed, so nevermind.

**Comment by carmenbianca** [comment]
@huguesdk 

Could you review [05b33a6](https://github.com/coopiteasy/cie-timesheet/pull/16/commits/05b33a695c6370da09c4a47f90e2b571c3ad9407)?

Link to screenshot that shows the issue fixed by the commit: https://framateam.org/coopiteasy/pl/xh1ycipbi3n498re39kzhm5xgw

**Review by huguesdk — COMMENTED** [review]
storing these fields is tricky to get right. the overtime depends on many variables:
*   the timesheet lines and their amount
*   the current date
*   the contracts of the employee (their state, start and end date)
*   the working time linked to the contracts
*   possibly other things that don’t come to mind right away

although i think it would be very useful to be able to store the overtime, because it would massively improve the performance when accessing these fields and allow things like pivot views or totals, it should only be done after a thorough test suite has been created to ensure it is correctly recomputed when any of the variables changes.

**Comment by carmenbianca** [comment]
Removing latest commit. Posting the patch here for posterity's sake. May work on it later.

```patch
From 05b33a695c6370da09c4a47f90e2b571c3ad9407 Mon Sep 17 00:00:00 2001
From: Carmen Bianca Bakker <carmen@coopiteasy.be>
Date: Wed, 25 May 2022 17:38:08 +0200
Subject: [PATCH] [ADD] hr_timesheet_overtime: Store computed values
 working_time and timesheet_overtime

This is technically not very useful; these values will be recomputed
every time a new thing is timesheeted. However, it allows you to
aggregate all working hours and overtime hours when using 'group by' in
the timesheet tree view.

Signed-off-by: Carmen Bianca Bakker <carmen@coopiteasy.be>
---
 hr_timesheet_overtime/models/hr_timesheet_sheet.py | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/hr_timesheet_overtime/models/hr_timesheet_sheet.py b/hr_timesheet_overtime/models/hr_timesheet_sheet.py
index 39c65d0..5baa692 100644
--- a/hr_timesheet_overtime/models/hr_timesheet_sheet.py
+++ b/hr_timesheet_overtime/models/hr_timesheet_sheet.py
@@ -23,6 +23,7 @@ class HrTimesheetSheet(models.Model):
         "Working Hours",
         compute="_compute_working_time",
         help="Hours to work for the timesheet period",
+        store=True,
     )
     daily_overtime = fields.Float(
         "Daily Overtime",
@@ -33,6 +34,7 @@ class HrTimesheetSheet(models.Model):
         "Timesheet Overtime",
         compute="_compute_timesheet_overtime",
         help="Overtime for this timesheet period",
+        store=True,
     )
     timesheet_overtime_trimmed = fields.Float(
         "Trimmed Timesheet Overtime",
@@ -67,6 +69,7 @@ class HrTimesheetSheet(models.Model):
         return sum(line.unit_amount for line in aal)
 
     @api.multi
+    @api.depends("timesheet_ids.unit_amount")
     def _compute_working_time(self):
         for sheet in self:
             sheet.working_time = sheet.employee_id.get_working_time(
@@ -85,6 +88,7 @@ class HrTimesheetSheet(models.Model):
             sheet.daily_overtime = worked_time - working_time
 
     @api.multi
+    @api.depends("total_time", "working_time")
     def _compute_timesheet_overtime(self):
         for sheet in self:
             sheet.timesheet_overtime = sheet.total_time - sheet.working_time
-- 
2.36.1
```

**Comment by carmenbianca** [comment]
@huguesdk

> storing these fields is tricky to get right. the overtime depends on many variables:
> *   the timesheet lines and their amount

The dependency on `timesheet_ids.unit_amount` is also used by `total_time` upstream, so that should be fine.

> *   the current date

Not needed for the altered fields. Would be needed for `timesheet_overtime_trimmed`, but we're not storing that one.

> *   the contracts of the employee (their state, start and end date)
> *   the working time linked to the contracts

Agreed

> *   possibly other things that don’t come to mind right away

Not entirely sure.

I'll have a look at implementing this now.

**Pull request merged**
