### PR TITLE
[ADD] hr_timesheet_project_prevent_creation

### PR DESCRIPTION
**Pull request by carmenbianca**
## Description

Related to line 23 of the Migration_v12_Odoo document.

See also #23

## Odoo task (if applicable)

https://gestion.coopiteasy.be/web#id=9087&action=479&model=project.task&view_type=form&menu_id=

## Checklist before approval

- [ ] Tests are present (or not needed).
- [x] Credits/copyright have been changed correctly.
- [ ] (If a new module) Moving this to OCA has been considered.

### CODE REVIEW

**Review by huguesdk — CHANGES_REQUESTED** [review]
lgtm, but i think that the change to `hr_timesheet_task_change_project` should go in its own pull request, since it’s related to another module. like that, ocabot will be able to bump the version number.

**Comment by carmenbianca** [comment]
@huguesdk agreed + done, see #23

**Review by huguesdk — APPROVED** [review]
thanks! lgtm! should the pull request be renamed as `[ADD] hr_timesheet_project_prevent_creation`?

**Pull request merged**
